mod 'camptocamp-systemd', :latest
mod 'puppet-hiera', :latest
mod 'puppet-letsencrypt', :latest
mod 'puppet-r10k', :latest
mod 'puppet-selinux', :latest
mod 'puppet-ssh_keygen', :latest
mod 'puppetlabs-apache', :latest
mod 'puppetlabs-concat', :latest
mod 'puppetlabs-git', :latest
mod 'puppetlabs-inifile', :latest
mod 'puppetlabs-postgresql', :latest
mod 'puppetlabs-ruby', :latest
mod 'puppetlabs-stdlib', :latest
mod 'puppetlabs-translate', :latest
mod 'puppetlabs-vcsrepo', :latest
