mod 'camptocamp-systemd', :latest
mod 'puppet-letsencrypt', :latest
mod 'puppet-r10k', :latest
mod 'puppet-ssh_keygen', :latest
mod 'puppetlabs-git', :latest
mod 'puppetlabs-inifile', :latest
mod 'puppetlabs-ruby', :latest
mod 'puppetlabs-stdlib', :latest
mod 'puppetlabs-translate', :latest
mod 'puppetlabs-vcsrepo', :latest
